services:
  app:
    container_name: portfolio-app
    build:
      context: .
      target: production
    restart: unless-stopped
    env_file: .env
    working_dir: /app
    networks:
      - portfolio-network

  database:
    image: postgres
    container_name: portfolio-database
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - portfolio-network

  adminer:
    image: adminer
    container_name: portfolio-adminer
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
